#!/bin/bash
# shellcheck disable=SC2139

alias vi="vim"
alias mtr='mtr -o "LRDS N BAW" '
alias diff="colordiff"
alias lsd='ls --group-directories-first'
alias nmon='NMON="cmtu" nmon'
alias lock="qdbus org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.Lock"
alias afk="qdbus org.freedesktop.ScreenSaver /org/freedesktop/ScreenSaver Lock"
alias ocat='/usr/bin/cat'  # TODO: check if still needed

# IP addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\\.){3}[0-9]*' | grep -Eo '([0-9]*\\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\\? \\(addr:\\)\\?\\s\\?\\(\\(\\([0-9]\\+\\.\\)\\{3\\}[0-9]\\+\\)\\|[a-fA-F0-9:]\\+\\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Home PCs
alias gamingpc="wol 24:4b:fe:89:cf:ab"
alias aduspc="wol d0:50:99:9a:f5:8c"
