#!/bin/bash

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{aliases,functions,extra,exports,kubernetes,golang}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		# shellcheck source=/dev/null
		source "$file"
	fi
done
unset file

# Load secret variables and check their staleness
if [ -f "$HOME/.secrets/bash_vars" ]; then
	last_mod=$(date +%s -r "$HOME/.secrets/bash_vars")
	# rotation every 45 days
	if [ "$((last_mod + 3888000))" -gt "$(date +%s)" ]; then
		# shellcheck source=/dev/null
		source "$HOME/.secrets/bash_vars"
	else
		echo -e "\e[1m\e[5m\e[31mALERT! \e[25mCredentials are older than 45 days and were not loaded.\e[0m"
	fi
	unset last_mod
fi

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null
done

# Add tab completion for SSH hostnames based on ~/.ssh/config
# ignoring wildcards
[[ -e "$HOME/.ssh/config" ]] && complete -o "default" \
	-o "nospace" \
	-W "$(grep "^Host" ~/.ssh/config | \
	grep -v "[?*]" | cut -d " " -f2 | \
	tr ' ' '\n')" scp sftp ssh

# print a fortune when the terminal opens
#fortune -a -s | lolcat
