#!/bin/bash

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{aliases,functions,extra,exports,gpg-ssh,kubernetes,golang}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		# shellcheck source=/dev/null
		source "$file"
	fi
done
unset file

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null
done

# print a fortune when the terminal opens
#fortune -a -s | lolcat

# Load secret variables when not stale
secrets-load

# check if there is newer kernel installed
checkkernel

# ensure proper xmodmap mapping
(xmodmap | grep locka &>/dev/null) || xmodmap "$HOME/.Xmodmap"

# Show what I need to do next
todo
