#!/bin/bash

function sshcopyid() {
	local host
	host="$1"
	ssh-copy-id "$host"
	for id in "$HOME/.ssh/id_rsa.pub" "$HOME/.ssh/ankhmorpork.pub"; do
		echo "$id"
		ssh-copy-id -f -i "$id" "$host"
	done
}

function gpgreload() {
	local keyid="0x507ED6F6586DD37F"
	gpgconf --kill gpg-agent
	# shellcheck disable=SC2164
	( cd "$(gpgconf --list-dirs homedir)/private-keys-v1.d"; 
	gpg2 -K --with-keygrip --with-colons "$keyid" | \
	awk -F: '/^grp/ { print $10".key"; }' | \
	xargs rm -vf >/dev/null; )
	gpg-connect-agent "scd serialno" "learn --force" /bye >/dev/null 2>&1
}
