#!/bin/bash

# -- EXPORTS --
export KUBECONFIG="${HOME}/.kube/config"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# -- AUTOCOMPLETIONS --
if command -v kubectl &>/dev/null; then
	# shellcheck source=/dev/null
	source <(kubectl completion bash)
	complete -F __start_kubectl k
fi

if command -v kind &>/dev/null; then
	# shellcheck source=/dev/null
	source <(kind completion bash)
fi

if command -v kubecolor &>/dev/null; then
  alias kubectl="kubecolor"
  complete -o default -F __start_kubectl kubecolor
fi

# -- ALIASES --
if ! command -v oc &>/dev/null; then
	alias oc=kubectl
fi
alias k=kubectl

alias kube-lint="kube-linter lint"

alias kube-rim="export KUBECONFIG=${HOME}/.kube/rim-kubeconfig.yaml"
alias kube-kind="export KUBECONFIG=${HOME}/.kube/kind-cluster-kind.yaml"
alias kube-ankh="export KUBECONFIG=${HOME}/.kube/config.ankhmorpork.yaml"
alias kube-clusterbot="export KUBECONFIG=${HOME}/.kube/config.clusterbot"
alias kube-reset="export KUBECONFIG=${HOME}/.kube/config"

# -- FUNCTIONS --

# TODO: kubectl plugin ?
function k8s-show-image() {
	kubectl get pods --all-namespaces -l app="${1}" -ojsonpath="{.items[*].spec.containers[?(@.name==\"$1\")].image}"
}

# TODO: kubectl plugin?
function k8s-po-show-rules() {
	kubectl -n prometheus-operator-e2e-tests exec -it prometheus-test-0 -c prometheus '/bin/sh -c "cat /etc/prometheus/rules/rules-0/test.rules"'
}
