#!/bin/sh

# go path
export GOPATH="${HOME}/Projects/go"
#export GOPATH="${HOME}/.go"

# update path
export PATH=/usr/local/bin:/usr/local/go/bin:${PATH}:${GOPATH}/bin:/sbin

# update cdpath
export CDPATH=${CDPATH}:$GOPATH/src/github.com:$GOPATH/src/golang.org:$GOPATH/src:/home/paulfantom/Projects
