#!/bin/bash

IF="$1"
STATUS="$2"
ESSID="Now you see me"
HOST="nas.ankhmorpork"

if [ "$IF" == "wlan0" ]; then
  case "$STATUS" in
  up)
    if iwgetid | grep -qs ":\"$ESSID\""; then
      mount "${HOST}:/srv/tv" /mnt/nas/tv
      mount "${HOST}:/srv/pictures" /mnt/nas/pictures
      mount "${HOST}:/srv/downloads" /mnt/nas/downloads
      mount "${HOST}:/srv/movies" /mnt/nas/movies
      mount "${HOST}:/srv/videos" /mnt/nas/videos
    fi
    ;;
  down|pre-down)
    umount -lf /mnt/nas/tv
    umount -lf /mnt/nas/pictures
    umount -lf /mnt/nas/downloads
    umount -lf /mnt/nas/movies
    umount -lf /mnt/nas/videos
    ;;
  esac
fi

exit 0
